# Use postgres/example user/password credentials
version: "3.8"

services:
  db:
    image: postgres:16.4
    restart: always
    env_file: .env
    ports:
      - "5433:5432" # Mapea el puerto 5432 del contenedor al puerto 5433 de la máquina
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistencia de datos

volumes:
  postgres-data:
